from .catalog_knowledge import CATALOG_KNOWLEDGE_BASE, ATTRIBUTE_SEARCH_SYNONYMS
from .catalog_taxonomy import CATALOG_TAXONOMY_BLOCK, WEB_TAXONOMY_BLOCK
from .prompt_templates import (
    CLARIFICATION_TEMPLATE,
    TECHNICAL_RESPONSE_TEMPLATE,
    CATEGORY_LIST_TEMPLATE,
    NOT_SOLD_TEMPLATE,
    ATTRIBUTE_PRODUCT_TEMPLATE,
    ATTRIBUTE_FAMILY_TEMPLATE,
)

__all__ = [
    "CATALOG_KNOWLEDGE_BASE",
    "ATTRIBUTE_SEARCH_SYNONYMS",
    "CATALOG_TAXONOMY_BLOCK",
    "TECHNICAL_RESPONSE_TEMPLATE",
    "CLARIFICATION_TEMPLATE",
    "CATEGORY_LIST_TEMPLATE",
    "NOT_SOLD_TEMPLATE",
    "ATTRIBUTE_PRODUCT_TEMPLATE",
    "ATTRIBUTE_FAMILY_TEMPLATE",
    "WEB_TAXONOMY_BLOCK",
]
